# Generated by Django 5.0.6 on 2024-07-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("usn", models.CharField(max_length=20)),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("cs", "Computer Science (CS)"),
                            ("ec", "Electronics and Communication (EC)"),
                            ("ee", "Electrical Engineering (EE)"),
                            ("me", "Mechanical Engineering (ME)"),
                            ("cv", "Civil Engineering (CV)"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "question1",
                    models.CharField(
                        choices=[
                            ("Excellent", "Excellent"),
                            ("Good", "Good"),
                            ("Average", "Average"),
                            ("Poor", "Poor"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "question2",
                    models.CharField(
                        choices=[
                            ("Excellent", "Excellent"),
                            ("Good", "Good"),
                            ("Average", "Average"),
                            ("Poor", "Poor"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "question3",
                    models.CharField(
                        choices=[
                            ("Excellent", "Excellent"),
                            ("Good", "Good"),
                            ("Average", "Average"),
                            ("Poor", "Poor"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "question4",
                    models.CharField(
                        choices=[
                            ("Excellent", "Excellent"),
                            ("Good", "Good"),
                            ("Average", "Average"),
                            ("Poor", "Poor"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "question5",
                    models.CharField(
                        choices=[
                            ("Excellent", "Excellent"),
                            ("Good", "Good"),
                            ("Average", "Average"),
                            ("Poor", "Poor"),
                        ],
                        max_length=10,
                    ),
                ),
                ("additional_feedback", models.TextField()),
            ],
        ),
    ]
