# Generated by Django 5.0.6 on 2024-06-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
